# The Easy Method

This book's objective is directing you into a new frame of mind. In contrast to the usual method of stopping — whereby you start off with the feeling of climbing Mount Everest and spend the next few weeks craving and feeling deprived — you start right away with a feeling of elation, as if cured of a terrible disease. From then on, the further you go through life, the more you will look at this period of time and wonder how you ever used any short-form content in the first place. You will look at other short-form users with pity, as opposed to envy.

Provided that you're not someone who had never become addicted (reading for your significant other) or had quit (or is in the fasting days of a “scrolling diet”), it's essential to keep using until you have finished the book completely. This may appear to be a contradiction, and this instruction to continue scrolling to short-form content causes more objection than any other, but as you read further your desire to use short-form content will gradually be reduced. **Take this instruction seriously: Attempting to quit early will not benefit you.**

Many don't finish the book because they feel they have to give something up, some even deliberately only reading one line per day in order to postpone the evil event. Look at it this way, what have you got to lose? If you don't stop at the end of the book, you’re no worse off than you are now. It's by definition a Pascal's Wager, a bet taken where you have nothing to lose and high chances of large gains.

Incidentally, if you haven't watched short-form content for a few days or weeks, but aren't sure whether you’re a short-form user, ex-user, or a non-user; or you find your desire to watch short-form content has dwindled as you're absorbing the material, then don't use short-form content to scroll whilst reading. In fact, you’re already a non-user, but we have to let your brain catch up with your body. By the end of the book, you’ll be a happy non-user. EasyPeasy is the complete opposite of the normal method, where one lists the considerable disadvantages of short-form content and says:
*“If only I can go long enough without short-form content, eventually the desire will go and I can enjoy life again, free of slavery.”*
This is the logical way to go about it, with thousands stopping every day using this method. However, it's very difficult to succeed for the following reasons:

**Stopping short-form loop isn’t the real problem.**
Every time you finish your session, you've stopped using it. You may have powerful reasons on the first day of your once-in-four scrolling diet to say *“I don’t want to use short-form content, or even scroll any more.”* All users do, and their reasons are more powerful than you can possibly imagine. The real problem is day two, ten, or ten-thousand where in a weak moment you’ll have ‘just one peek’, want another, and suddenly you’re an addict again.

**Awareness of the health risks generates more fear, making it more difficult to stop.**
Tell a user it's destroying their confidence and the first thing they’ll do is reach for something to surge their dopamine: a cigarette, alcohol, or even firing up the browser to search for short-form content.

**All reasons for stopping actually make it harder.**
This is due to two reasons. First, we’re continually being forced to give up our ’little friend’ or some prop, vice, or pleasure (whichever way the user perceives it). Second, they create a “blind”. We do not scroll for the reasons we should stop. The real question is, why do we want or need to do it?

With EasyPeasy, we (initially) forget the reasons we'd like to stop, face the short-form content problem and ask ourselves the following questions:

1.  What is short-form content doing for me?

2.  Am I actually enjoying it?

3.  Do I really need to go through life sabotaging my mind and body?

The beautiful truth is that *all short-form content* does absolutely nothing for you whatsoever. Let me make it quite clear, it's not that the disadvantages of being a user outweigh the advantages, it's that there are ***zero*** advantages to looking at short-form content.

Most users find it necessary to rationalise why they use short-form content, but the reasons they come up with are all fallacies and illusions.

First, we'll remove these fallacies and illusions. In fact, you'll soon realise there is nothing to give up. Not only that, but there are marvellous, positive gains from being a non-short-form user, with well-being and happiness only two of these gains. Once illusions that life will never be quite as enjoyable without short-form content is removed — realising that not only is life just as enjoyable without it but infinitely more so — and once feelings of being deprived or missing out are eradicated, we'll go back to reconsider increased well-being and happiness — and the dozens of other reasons for quitting short-form content. These realisations will become positive additional aids to help you achieve what you really desire: enjoying your life free from the slavery of short-form addiction!
