# Can I Compartmentalise?

This myth is primarily spread by users attempting to stop on the willpower method, who perform mental gymnastics and begin a Jekyll-and-Hyde routine: “*Short-form content is for my alter ego and real-life romance is for my relationship side.*" Nothing is further from the truth — the short-form water slides, DeltaFosB and neurological changes are going to overrun the real-life romance, making it less desirable. Mr Hyde is definitely going to overrule Dr Jekyll's instructions.

If you use short-form content, you're training yourself for the role of voyeur, or requiring the option of clicking to something more arousing at the slightest drop in dopamine levels. Or, the continual search for *just* the right scene for maximum effect. Additionally, you might be scrolling in a hunched-over position or watching your smartphone at home on the nightly, eventually desiring those cues more than real-life stimuli. Real life goes against nearly every aspect of the endless feed, so it stands no chance when compared. The memories created when you're young are powerful and long-lasting, so breaking down those short-form water slides and rewiring or creating new ones takes longer. However, that's not to say it's any more difficult.

Every time you ride on the ‘short-form water slide' you're greasing it, keeping the nerves fresh and ready to fire. When parking next to a fast-food restaurant, the smell of the fryer floats into your nostrils and the sale is already made. Likewise, the short-form water slides in your brain are ready for you to get sucked in and are open twenty-four hours a day. Each cue or trigger lights up your reward circuit with the promise of connection — only it isn't connection. Nevertheless, nerve cells solidify these associations with social motivation by sprouting new branches to strengthen the connections. The more you use short-form content, the stronger the nerve connections become. The end result is that you might ultimately *need* to be a voyeur, needing to click to ever-escalating and novel material, needing short-form content to get to sleep, or needing to search for the perfect ending to get the job done.

As with any substance or behavioral drug, the body builds tolerance and the drug ceases to relieve the withdrawal pangs completely. As soon as the short-form user closes a session, they want another one, and quickly, the permanent hunger remaining unsatisfied. The natural inclination is escalation, to get the dopamine rush. However, most users are prevented from doing this for either or both of the following reasons.

**Money:** They can't afford to subscribe to paid short-form apps.

**Health:** There's only so much the body can take, either the dopamine surges or dopamine hits. Plus, dopamine hits can trigger chemicals in order to cut down the dopamine flush. It has to, that's just the way the body works.

Once the little monster leaves your body, the awful feeling of insecurity ends. Your confidence returns, along with a marvellous feeling of self-respect, obtaining the assurance to take control of your life and using it as a springboard to tackle other problems. This is one of the many great advantages of breaking free from any addiction.

The compartmentalisation myth is one of many tricks that the little monster plays with your mind. These tricks make it harder to stop — due to the impossible satisfaction of the permanent hunger — causing many users to turn to cigarettes, heavy drinking, or even harder drugs to satisfy the void.

Humans are rating animals, both to ourselves and others. Watching short-form content with your partner is unsatisfying, as you both rate each other's performance against the narrative. Do you want Brad Pitt in your bedroom, even if he's on a poster? No one person can match a feed where each ‘experience' is acted, scripted, directed by professionals and immediately available twenty-four hours a day.
