# The Instructions

1.  Follow all instructions.

2.  Keep an open mind.

3.  Start with a feeling of elation.

4.  Ignore all advice and influence that conflicts with EasyPeasy.

5.  Resist any promise of a temporary fix.

6.  Get it clear in your mind: short-form content provides no genuine pleasure or crutch and you aren't making a sacrifice. There's nothing to give up and no reason to feel deprived.

7.  Don't wait to quit, do it now!

8.  Make a decision never to watch again and never question it.

9.  Remember there is no such thing as just one peek.

10. Never watch short-form content again.

## Affirmations

-   I'm free from the slavery of short-form content.

-   It's easy to ignore my thoughts about short-form content.

-   Bye-bye thoughts, bye-bye urges. Oh, there go my cravings.

-   I focus my subconscious mind to overcome short-form addiction.

-   Short-form content steals my time, energy and vitality.

-   Beating short-form content gets exponentially easier day by day and in every aspect.

-   I enjoy and value my short-form-content-free, strong, happy, light and easy lifestyle.

-   If I look back and think about my progress, it gives me great joy and pride in myself.

-   Every time I see other short-form users I get more motivated to see myself break that chain.

-   All that pent-up energy is healing my body and mind. Then, I can do more productive and challenging work towards my values and goals.

-   My brain is getting back in correct shape, getting exercised by me *not* doing what I was previously doing.

-   Now all that pent-up willpower is being used to handle lightweight stresses and strains of life.

-   Great, I'm free and no longer a slave!
